name: ci

on:
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            configure_preset: linux-debug
            build_preset: linux-debug
            test_preset: linux-debug
          - os: macos-latest
            configure_preset: macos-debug
            build_preset: macos-debug
            test_preset: macos-debug
          - os: windows-latest
            configure_preset: windows-debug
            build_preset: windows-debug
            test_preset: windows-debug

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        if: runner.os != 'Windows'
        shell: bash
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Install uv
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          irm https://astral.sh/uv/install.ps1 | iex
          "$env:USERPROFILE\.local\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Configure
        run: cmake --preset ${{ matrix.configure_preset }}

      - name: Build
        run: cmake --build --preset ${{ matrix.build_preset }} --parallel

      - name: Test
        run: ctest --preset ${{ matrix.test_preset }}
